#!/usr/bin/env python3
"""
ziiagentmemory rebrand v2 — surgical, safe bulk substitution.

Lessons from v1:
- "ziiagentmemory" must NEVER get re-passed through prose subs
- <th>agentmemory</th> in benchmark tables = upstream product, KEEP
- trendshift/star-history URLs read from external services, KEEP
- Only rebrand the identity surfaces and CLI commands; leave prose mostly alone

Approach: targeted subs only, using a careful ordered list with explicit
"preserve" markers, no broad prose rebrand.
"""
from __future__ import annotations
import re, sys
from pathlib import Path

ROOT = Path("C:/Projects/ziiagentmemory")

# Files to NEVER touch.
SKIP_FILES = {
    "LICENSE",
    "NOTICE",
    "ziiagentmemory_rebrand.py",
    "package-lock.json",  # auto-regenerated by npm
    "CHANGELOG.md",      # upstream hard rule: never touch CHANGELOG
    "test-results.log",  # ephemeral test artifact
}

SKIP_DIRS = {
    "node_modules", "dist", ".git", ".next", ".vercel",
    "site_data", "benchmark/node_modules", "website/node_modules",
    "website/.next",
}

# Patterns as (regex, replacement). Regex must be ordered: most specific first
# so we don't accidentally re-match. Use \b word boundaries aggressively.
SUBS: list[tuple[str, str]] = [
    # --- npm / package identity (longest first) ---
    (r"@agentmemory/agentmemory", "ziiagentmemory"),

    # --- standalone MCP sub-package reference ---
    (r"@agentmemory/mcp", "ziiagentmemory"),  # we don't ship a separate mcp pkg

    # --- repo URLs (org/repo shorthand and full URL) ---
    # KEEP external service URLs pointing at the original:
    #   trendshift.io, star-history.com, gist.github.com, raw.githubusercontent
    # But replace the canonical https://github.com/rohitg00/agentmemory path
    (r"https://github\.com/rohitg00/agentmemory(?=[\s/\"'\)])", "https://github.com/ziishanahmad/ziiagentmemory"),
    (r"rohitg00/agentmemory(?=[\s\"/\)\.])",                  "ziishanahmad/ziiagentmemory"),

    # --- env var prefix (longest first, exact match) ---
    (r"\bAGENTMEMORY_LLM_TIMEOUT_MS\b", "ZIIAGENTMEMORY_LLM_TIMEOUT_MS"),
    (r"\bAGENTMEMORY_ALLOW_AGENT_SDK\b", "ZIIAGENTMEMORY_ALLOW_AGENT_SDK"),
    (r"\bAGENTMEMORY_SECRET\b",         "ZIIAGENTMEMORY_SECRET"),
    (r"\bAGENTMEMORY_REFLECT\b",        "ZIIAGENTMEMORY_REFLECT"),
    (r"\bAGENTMEMORY_SLOTS\b",          "ZIIAGENTMEMORY_SLOTS"),
    (r"\bAGENTMEMORY_AUTO_COMPRESS\b",  "ZIIAGENTMEMORY_AUTO_COMPRESS"),
    (r"\bAGENTMEMORY_DROP_STALE_INDEX\b","ZIIAGENTMEMORY_DROP_STALE_INDEX"),
    (r"\bAGENTMEMORY_URL\b",            "ZIIAGENTMEMORY_URL"),
    # Catch-all for any remaining AGENTMEMORY_* env vars (must be a single
    # capture group; the named form below this is the canonical one).
    (r"\bAGENTMEMORY_([A-Z][A-Z0-9_]*)\b", r"ZIIAGENTMEMORY_\1"),

    # --- config dir (longest first) ---
    (r"~\/\.agentmemory",  "~/.ziiagentmemory"),
    (r"USERPROFILE\\\\\.agentmemory", r"USERPROFILE\\\\.ziiagentmemory"),  # not present likely

    # --- HTTP path prefix (in docs/code, NOT external URLs) ---
    # Match /agentmemory/<word> preceded by anything except 'zii' (to avoid
    # eating ziiagentmemory/agentmemory). Use simple /agentmemory/ with
    # lookbehind for 'zii'.
    (r"(?<!zii)/agentmemory/", "/ziiagentmemory/"),
    # Standalone /agentmemory (rare; without trailing slash)
    (r"(?<!zii)/agentmemory(?=[\s\"'<>\)])", "/ziiagentmemory"),

    # --- install/run commands ---
    (r"npm install -g @agentmemory/agentmemory",
     "npm install -g ziiagentmemory"),
    (r"npm i -g @agentmemory/agentmemory",
     "npm i -g ziiagentmemory"),
    (r"npx -y @agentmemory/agentmemory@latest",
     "npx -y ziiagentmemory@latest"),
    (r"npx @agentmemory/agentmemory@latest",
     "npx ziiagentmemory@latest"),
    (r"npx -y @agentmemory/agentmemory",
     "npx -y ziiagentmemory"),
    (r"npx @agentmemory/agentmemory",
     "npx ziiagentmemory"),
    (r"npx -y @agentmemory/mcp",
     "npx -y ziiagentmemory"),

    # --- CLI command invocations ---
    # "agentmemory connect claude-code" etc — be careful not to match prose
    # like "agentmemory is the implementation". Use word boundary on the right.
    # These are usually at start of line or after backtick/space in command
    # contexts. Match `agentmemory` followed by a subcommand verb.
    (r"\bagentmemory\s+(connect|demo|doctor|upgrade|stop|remove|start|version|help|import-jsonl|export|export-jsonl|init|server|status)\b",
     r"ziiagentmemory \1"),
]


# Limited prose rebrand — only the user-facing brand at the start of
# sentences / headings / table headers. Be strict about boundaries.
# The "agentmemory" word must NOT be preceded by 'zii' (already done) and
# must not be part of a longer identifier.
PROSE_SUBS: list[tuple[str, str]] = [
    # Heading starts: "## agentmemory" -> "## ZiiAgentMemory"
    (r"(?m)^#\s+agentmemory\b",       "# ZiiAgentMemory"),
    # Backtick brand: `agentmemory` -> `ziiagentmemory` (binary, package)
    (r"`agentmemory`",                "`ziiagentmemory`"),
    # Sentence-initial agentmemory (start of line) -> ZiiAgentMemory
    (r"(?m)^agentmemory\b",           "ZiiAgentMemory"),
    # "the agentmemory" / "agentmemory + " / "agentmemory's" -> "ZiiAgentMemory"
    (r"(?<!zii)\bagentmemory\b",      "ZiiAgentMemory"),
]


def is_skip_path(p: Path) -> bool:
    rel = p.relative_to(ROOT)
    parts = set(rel.parts)
    if parts & SKIP_DIRS:
        return True
    if p.name in SKIP_FILES:
        return True
    # skip binary / non-text
    try:
        p.read_text(encoding="utf-8")
        return False
    except (UnicodeDecodeError, OSError):
        return True


def apply_subs(text: str, table: list[tuple[str, str]]) -> tuple[str, int]:
    n = 0
    for pat, repl in table:
        new, c = re.subn(pat, repl, text)
        if c > 0:
            text = new
            n += c
    return text, n


def main():
    if not ROOT.exists():
        print(f"FATAL: {ROOT} not found", file=sys.stderr)
        sys.exit(2)

    all_files = [p for p in ROOT.rglob("*") if p.is_file()]
    targets = sorted(p for p in all_files if not is_skip_path(p))
    skipped = [p for p in all_files if p not in targets]

    print(f"Root:      {ROOT}")
    print(f"Total:     {len(all_files)}")
    print(f"Skipped:   {len(skipped)}")
    print(f"Targets:   {len(targets)}")
    print()

    grand = 0
    files_changed = 0

    for path in targets:
        rel = path.relative_to(ROOT)
        original = path.read_text(encoding="utf-8")

        new, n1 = apply_subs(original, SUBS)
        new, n2 = apply_subs(new, PROSE_SUBS)

        total = n1 + n2
        if total > 0:
            path.write_text(new, encoding="utf-8", newline="")
            files_changed += 1
            grand += total
            if files_changed <= 30 or total > 10:
                print(f"  {rel}  -> {total}")

    print()
    print("=" * 60)
    print(f"Files changed:      {files_changed}")
    print(f"Total replacements: {grand}")


if __name__ == "__main__":
    main()
